### ISSUE TITLE
Refactoring proposal: Remove parameter Assignments

### ISSUE THREAD

**Issue by samendoz** [janevegeorge/CodeRefactoring#2]
ShoppingCart.java

![image](https://user-images.githubusercontent.com/66740101/91245523-42d6f500-e713-11ea-81c5-a43ec2c58eb8.png)

**Comment by janevegeorge** [comment]
@samendoz Your refactoring is correct. These code smells have been intentionally added to this project for practice. Another best practice is to make the input parameters as final in Java.
